title: MESA Down Under 2024 WD Binaries Lab
description: what it says on the tin
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one